// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Key exists:', !!SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage that handles both localStorage and memory
const createBrowserStorage = () => {
  const hasLocalStorage = typeof window !== 'undefined' && window.localStorage;
  
  return {
    getItem: (key: string): string | null => {
      if (!hasLocalStorage) return null;
      try {
        return localStorage.getItem(key);
      } catch (error) {
        console.warn('localStorage getItem error:', error);
        return null;
      }
    },
    setItem: (key: string, value: string): void => {
      if (!hasLocalStorage) return;
      try {
        localStorage.setItem(key, value);
      } catch (error) {
        console.warn('localStorage setItem error:', error);
      }
    },
    removeItem: (key: string): void => {
      if (!hasLocalStorage) return;
      try {
        localStorage.removeItem(key);
      } catch (error) {
        console.warn('localStorage removeItem error:', error);
      }
    },
  };
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createBrowserStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // More secure and works better across different browsers
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js/2.x',
    },
  },
});

// Test connection (non-blocking)
const testConnection = async () => {
  try {
    const { error } = await supabase.auth.getSession();
    console.log('Supabase connection:', error ? 'FAILED' : 'SUCCESS');
    if (error) console.error('Connection error:', error);
  } catch (err) {
    console.error('Supabase connection test failed:', err);
  }
};

// Don't await - let it run in background
testConnection();